/**
 * GENERATED by scripts/generate-cardinal.mjs -- do not edit.
 *
 * Source of truth: cardinal/components.mjs
 * Regenerate with: node scripts/generate-cardinal.mjs
 */

/** Wire-level description of one component: no ECS, no Three.js. */
export interface CardinalCodec {
  id: number;
  name: string;
  /** Constant — the wire format relies on it to skip records. */
  bytes: number;
  /**
   * Field names and slot counts, in declaration order.
   *
   * Exposed because a consumer that only has an id needs the structure to
   * make sense of a flat value list — the golden-vector reader is exactly
   * that case.
   */
  fields: readonly { name: string; slots: number }[];
  encode(view: DataView, offset: number, data: Record<string, unknown>): void;
  decode(view: DataView, offset: number): Record<string, unknown>;
}

/** Fingerprint of the schema these codecs came from. */
export const SCHEMA_HASH = 'b0c0459c';

/** Component 1, 8 bytes. */
export interface HealthData {
  current: number;
  max: number;
}

function encodeHealth(view: DataView, offset: number, data: Record<string, unknown>): void {
  view.setFloat32(offset + 0, (data.current as number), true);
  view.setFloat32(offset + 4, (data.max as number), true);
}

function decodeHealth(view: DataView, offset: number): Record<string, unknown> {
  return {
    current: view.getFloat32(offset + 0, true),
    max: view.getFloat32(offset + 4, true),
  };
}

/** Component 2, 16 bytes. */
export interface GrabbableData {
  holderId: number;
  grabPoint: number[];
}

function encodeGrabbable(view: DataView, offset: number, data: Record<string, unknown>): void {
  view.setUint32(offset + 0, (data.holderId as number), true);
  view.setFloat32(offset + 4, (data.grabPoint as number[])[0] ?? 0, true); view.setFloat32(offset + 4 + 4, (data.grabPoint as number[])[1] ?? 0, true); view.setFloat32(offset + 4 + 8, (data.grabPoint as number[])[2] ?? 0, true);
}

function decodeGrabbable(view: DataView, offset: number): Record<string, unknown> {
  return {
    holderId: view.getUint32(offset + 0, true),
    grabPoint: [view.getFloat32(offset + 4, true), view.getFloat32(offset + 4 + 4, true), view.getFloat32(offset + 4 + 8, true)],
  };
}

/** Component 3, 17 bytes. */
export interface WeatherData {
  kind: number;
  intensity: number;
  wind: number[];
}

function encodeWeather(view: DataView, offset: number, data: Record<string, unknown>): void {
  view.setUint8(offset + 0, (data.kind as number));
  view.setFloat32(offset + 1, (data.intensity as number), true);
  view.setFloat32(offset + 5, (data.wind as number[])[0] ?? 0, true); view.setFloat32(offset + 5 + 4, (data.wind as number[])[1] ?? 0, true); view.setFloat32(offset + 5 + 8, (data.wind as number[])[2] ?? 0, true);
}

function decodeWeather(view: DataView, offset: number): Record<string, unknown> {
  return {
    kind: view.getUint8(offset + 0),
    intensity: view.getFloat32(offset + 1, true),
    wind: [view.getFloat32(offset + 5, true), view.getFloat32(offset + 5 + 4, true), view.getFloat32(offset + 5 + 8, true)],
  };
}

/** Component 4, 13 bytes. */
export interface CharacterGenomeData {
  genes: number[];
}

function encodeCharacterGenome(view: DataView, offset: number, data: Record<string, unknown>): void {
  {
    const items = data.genes as number[];
    for (let i = 0; i < 13; i++) {
      view.setUint8(offset + 0 + i * 1, items[i] ?? 0);
    }
  }
}

function decodeCharacterGenome(view: DataView, offset: number): Record<string, unknown> {
  return {
    genes: Array.from({ length: 13 }, (_unused, i) =>
      view.getUint8(offset + 0 + i * 1)),
  };
}

/** Every schema component's codec, keyed by its permanent wire id. */
export const CARDINAL_CODECS: ReadonlyMap<number, CardinalCodec> = new Map([
  [1, {
    id: 1,
    name: 'Health',
    bytes: 8,
    fields: [
      { name: 'current', slots: 1 },
      { name: 'max', slots: 1 },
    ],
    encode: encodeHealth,
    decode: decodeHealth,
  }],
  [2, {
    id: 2,
    name: 'Grabbable',
    bytes: 16,
    fields: [
      { name: 'holderId', slots: 1 },
      { name: 'grabPoint', slots: 3 },
    ],
    encode: encodeGrabbable,
    decode: decodeGrabbable,
  }],
  [3, {
    id: 3,
    name: 'Weather',
    bytes: 17,
    fields: [
      { name: 'kind', slots: 1 },
      { name: 'intensity', slots: 1 },
      { name: 'wind', slots: 3 },
    ],
    encode: encodeWeather,
    decode: decodeWeather,
  }],
  [4, {
    id: 4,
    name: 'CharacterGenome',
    bytes: 13,
    fields: [
      { name: 'genes', slots: 13 },
    ],
    encode: encodeCharacterGenome,
    decode: decodeCharacterGenome,
  }],
]);
