/**
 * GENERATED by scripts/generate-cardinal.mjs -- do not edit.
 *
 * Source of truth: cardinal/components.mjs
 * Regenerate with: node scripts/generate-cardinal.mjs
 */

import { Types, createComponent } from '@iwsdk/core';
import type { AnyComponent, Entity, World } from '@iwsdk/core';
import { TypedArrayMap } from 'elics';
import { CARDINAL_CODECS, type CardinalCodec } from './codecs.generated.js';

// elics ships only Vec2/Vec3/Vec4 (2/3/4-slot Float32Array) as multi-slot
// storage types — no generic N-slot integer array. `TypedArrayMap` is a
// plain, mutable, exported object (not a closed enum): registering an
// entry here, before any component below is registered, gives each array
// field a real, correctly-sized backing store instead of one borrowed
// from an unrelated vector type.
(TypedArrayMap as Record<string, { arrayConstructor: new (n: number) => object; length: number }>)['Array13U8'] = { arrayConstructor: Uint8Array, length: 13 };

/** A codec plus the ECS binding for the same component. */
export interface CardinalComponentSpec extends CardinalCodec {
  component: AnyComponent;
  read(entity: Entity): Record<string, unknown>;
  write(entity: Entity, data: Record<string, unknown>): void;
}

/** Component 1. */
export const Health = createComponent(
  'Health',
  {
    current: { type: Types.Float32, default: 0 },
    max: { type: Types.Float32, default: 0 },
  },
  'Cardinal component 1',
);

/** Component 2. */
export const Grabbable = createComponent(
  'Grabbable',
  {
    holderId: { type: Types.Int32, default: 0 },
    grabPoint: { type: Types.Vec3, default: [0, 0, 0] },
  },
  'Cardinal component 2',
);

/** Component 3. */
export const Weather = createComponent(
  'Weather',
  {
    kind: { type: Types.Int32, default: 0 },
    intensity: { type: Types.Float32, default: 0 },
    wind: { type: Types.Vec3, default: [0, 0, 0] },
  },
  'Cardinal component 3',
);

/** Component 4. */
export const CharacterGenome = createComponent(
  'CharacterGenome',
  {
    genes: { type: 'Array13U8' as any, default: new Array(13).fill(0) },
  },
  'Cardinal component 4',
);

/** Every schema component, keyed by its permanent wire id. */
export const CARDINAL_REGISTRY: ReadonlyMap<number, CardinalComponentSpec> = new Map([
  [1, {
    ...(CARDINAL_CODECS.get(1) as CardinalCodec),
    component: Health as unknown as AnyComponent,
    read: (entity: Entity) => ({
      current: entity.getValue(Health, 'current'),
      max: entity.getValue(Health, 'max'),
    }),
    write: (entity: Entity, data: Record<string, unknown>) => {
      entity.setValue(Health, 'current', data.current as never);
      entity.setValue(Health, 'max', data.max as never);
    },
  }],
  [2, {
    ...(CARDINAL_CODECS.get(2) as CardinalCodec),
    component: Grabbable as unknown as AnyComponent,
    read: (entity: Entity) => ({
      holderId: entity.getValue(Grabbable, 'holderId'),
      grabPoint: Array.from(entity.getVectorView(Grabbable, 'grabPoint')),
    }),
    write: (entity: Entity, data: Record<string, unknown>) => {
      entity.setValue(Grabbable, 'holderId', data.holderId as never);
      {
        const view = entity.getVectorView(Grabbable, 'grabPoint');
        const source = data.grabPoint as number[];
        for (let i = 0; i < 3; i++) view[i] = source[i] ?? 0;
      }
    },
  }],
  [3, {
    ...(CARDINAL_CODECS.get(3) as CardinalCodec),
    component: Weather as unknown as AnyComponent,
    read: (entity: Entity) => ({
      kind: entity.getValue(Weather, 'kind'),
      intensity: entity.getValue(Weather, 'intensity'),
      wind: Array.from(entity.getVectorView(Weather, 'wind')),
    }),
    write: (entity: Entity, data: Record<string, unknown>) => {
      entity.setValue(Weather, 'kind', data.kind as never);
      entity.setValue(Weather, 'intensity', data.intensity as never);
      {
        const view = entity.getVectorView(Weather, 'wind');
        const source = data.wind as number[];
        for (let i = 0; i < 3; i++) view[i] = source[i] ?? 0;
      }
    },
  }],
  [4, {
    ...(CARDINAL_CODECS.get(4) as CardinalCodec),
    component: CharacterGenome as unknown as AnyComponent,
    read: (entity: Entity) => ({
      genes: Array.from((entity as any).getVectorView(CharacterGenome, 'genes')),
    }),
    write: (entity: Entity, data: Record<string, unknown>) => {
      {
        const view = (entity as any).getVectorView(CharacterGenome, 'genes');
        const source = data.genes as number[];
        for (let i = 0; i < 13; i++) view[i] = source[i] ?? 0;
      }
    },
  }],
]);

/**
 * Register every Cardinal component on a world.
 *
 * Called by `installPhoenixNetworking`; an application only needs it
 * directly when building a world without the plugin.
 */
export function registerCardinalComponents(world: World): void {
  world.registerComponent(Health);
  world.registerComponent(Grabbable);
  world.registerComponent(Weather);
  world.registerComponent(CharacterGenome);
}
