/**
 * GENERATED by scripts/generate-cardinal.mjs -- do not edit.
 *
 * Source of truth: cardinal/components.mjs
 * Regenerate with: node scripts/generate-cardinal.mjs
 */

import { Types, createComponent } from '@iwsdk/core';
import type { AnyComponent, Entity, World } from '@iwsdk/core';
import { CARDINAL_CODECS, type CardinalCodec } from './codecs.generated.js';

/** A codec plus the ECS binding for the same component. */
export interface CardinalComponentSpec extends CardinalCodec {
  component: AnyComponent;
  read(entity: Entity): Record<string, unknown>;
  write(entity: Entity, data: Record<string, unknown>): void;
}

/** Component 1. */
export const Health = createComponent(
  'Health',
  {
    current: { type: Types.Float32, default: 0 },
    max: { type: Types.Float32, default: 0 },
  },
  'Cardinal component 1',
);

/** Component 2. */
export const Grabbable = createComponent(
  'Grabbable',
  {
    holderId: { type: Types.Int32, default: 0 },
    grabPoint: { type: Types.Vec3, default: [0, 0, 0] },
  },
  'Cardinal component 2',
);

/** Component 3. */
export const Weather = createComponent(
  'Weather',
  {
    kind: { type: Types.Int32, default: 0 },
    intensity: { type: Types.Float32, default: 0 },
    wind: { type: Types.Vec3, default: [0, 0, 0] },
  },
  'Cardinal component 3',
);

/** Every schema component, keyed by its permanent wire id. */
export const CARDINAL_REGISTRY: ReadonlyMap<number, CardinalComponentSpec> = new Map([
  [1, {
    ...(CARDINAL_CODECS.get(1) as CardinalCodec),
    component: Health as unknown as AnyComponent,
    read: (entity: Entity) => ({
      current: entity.getValue(Health, 'current'),
      max: entity.getValue(Health, 'max'),
    }),
    write: (entity: Entity, data: Record<string, unknown>) => {
      entity.setValue(Health, 'current', data.current as never);
      entity.setValue(Health, 'max', data.max as never);
    },
  }],
  [2, {
    ...(CARDINAL_CODECS.get(2) as CardinalCodec),
    component: Grabbable as unknown as AnyComponent,
    read: (entity: Entity) => ({
      holderId: entity.getValue(Grabbable, 'holderId'),
      grabPoint: Array.from(entity.getVectorView(Grabbable, 'grabPoint')),
    }),
    write: (entity: Entity, data: Record<string, unknown>) => {
      entity.setValue(Grabbable, 'holderId', data.holderId as never);
      {
        const view = entity.getVectorView(Grabbable, 'grabPoint');
        const source = data.grabPoint as number[];
        for (let i = 0; i < 3; i++) view[i] = source[i] ?? 0;
      }
    },
  }],
  [3, {
    ...(CARDINAL_CODECS.get(3) as CardinalCodec),
    component: Weather as unknown as AnyComponent,
    read: (entity: Entity) => ({
      kind: entity.getValue(Weather, 'kind'),
      intensity: entity.getValue(Weather, 'intensity'),
      wind: Array.from(entity.getVectorView(Weather, 'wind')),
    }),
    write: (entity: Entity, data: Record<string, unknown>) => {
      entity.setValue(Weather, 'kind', data.kind as never);
      entity.setValue(Weather, 'intensity', data.intensity as never);
      {
        const view = entity.getVectorView(Weather, 'wind');
        const source = data.wind as number[];
        for (let i = 0; i < 3; i++) view[i] = source[i] ?? 0;
      }
    },
  }],
]);

/**
 * Register every Cardinal component on a world.
 *
 * Called by `installPhoenixNetworking`; an application only needs it
 * directly when building a world without the plugin.
 */
export function registerCardinalComponents(world: World): void {
  world.registerComponent(Health);
  world.registerComponent(Grabbable);
  world.registerComponent(Weather);
}
