/**
 * Intent Security Guardrails & Anti-Prompt Injection Filter.
 * Validates intents against role-based security policies and sanitizes player speech.
 */

export interface IntentSecurityPolicy {
  /** List of permitted action names (e.g. ['GIVE_ITEM', 'ACCEPT_QUEST', 'ATTACK']) */
  allowedActions: string[];
  /** Explicitly forbidden action names */
  forbiddenActions?: string[];
  /** Parameter range and type validators */
  paramValidators?: Record<string, (val: any) => boolean>;
  /** Max allowed parameters per intent */
  maxParamsCount?: number;
}

export class IntentGuard {
  private static readonly INJECTION_PATTERNS = [
    /<\|(?:im_start|im_end|system|user|assistant)\|>/gi,
    /\[ACTION:[^\]]*\]/gi, // Strip raw player-injected action tags from input
    /###\s*(?:System|Instruction|Response):?/gi,
    /\[SYSTEM:?\]/gi,
  ];

  /**
   * Sanitize player spoken input or text to prevent prompt injection and tag forgery.
   */
  public static sanitizePlayerInput(rawInput: string): string {
    if (!rawInput) return '';
    let sanitized = rawInput;
    for (const pattern of this.INJECTION_PATTERNS) {
      sanitized = sanitized.replace(pattern, ' ');
    }
    return sanitized.trim();
  }

  /**
   * Validate whether an action intent generated by the LLM conforms to the NPC's security policy.
   */
  public static validateIntent(
    action: string,
    params: Record<string, string>,
    policy?: IntentSecurityPolicy
  ): { isValid: boolean; reason?: string } {
    const normalizedAction = action.toUpperCase().trim();

    if (!policy) {
      // Default safety: allow standard non-destructive actions
      return { isValid: true };
    }

    if (policy.forbiddenActions?.includes(normalizedAction)) {
      return {
        isValid: false,
        reason: `Action '${normalizedAction}' is explicitly forbidden by security policy`,
      };
    }

    if (policy.allowedActions.length > 0 && !policy.allowedActions.includes(normalizedAction)) {
      return {
        isValid: false,
        reason: `Action '${normalizedAction}' is not permitted for this NPC role`,
      };
    }

    if (policy.maxParamsCount !== undefined) {
      const keys = Object.keys(params);
      if (keys.length > policy.maxParamsCount) {
        return {
          isValid: false,
          reason: `Too many parameters for intent (${keys.length} > ${policy.maxParamsCount})`,
        };
      }
    }

    if (policy.paramValidators) {
      for (const [key, validator] of Object.entries(policy.paramValidators)) {
        if (key in params) {
          if (!validator(params[key])) {
            return {
              isValid: false,
              reason: `Parameter '${key}' with value '${params[key]}' failed validation`,
            };
          }
        }
      }
    }

    return { isValid: true };
  }

  /**
   * Retrieve pre-configured security policies for common RPG/VR roles.
   */
  public static getRolePolicy(role: 'merchant' | 'guard' | 'questgiver' | 'companion' | 'neutral'): IntentSecurityPolicy {
    switch (role) {
      case 'merchant':
        return {
          allowedActions: ['SELL_ITEM', 'BUY_ITEM', 'SHOW_INVENTORY', 'REFUSE_DEAL', 'EMOTE'],
          forbiddenActions: ['ATTACK', 'KILL_PLAYER', 'DELETE_ITEM', 'TELEPORT'],
          maxParamsCount: 4,
        };
      case 'guard':
        return {
          allowedActions: ['WARN_PLAYER', 'ATTACK', 'CALL_BACKUP', 'OPEN_GATE', 'CLOSE_GATE', 'EMOTE'],
          forbiddenActions: ['GIVE_GOLD', 'DELETE_ITEM'],
          maxParamsCount: 3,
        };
      case 'questgiver':
        return {
          allowedActions: ['OFFER_QUEST', 'COMPLETE_QUEST', 'GIVE_REWARD', 'SHOW_MAP_PIN', 'EMOTE'],
          forbiddenActions: ['ATTACK', 'KILL_PLAYER'],
          maxParamsCount: 4,
        };
      case 'companion':
        return {
          allowedActions: ['FOLLOW', 'STAY', 'ATTACK_TARGET', 'HEAL_PLAYER', 'GIVE_ITEM', 'EMOTE'],
          forbiddenActions: ['KILL_PLAYER'],
          maxParamsCount: 5,
        };
      case 'neutral':
      default:
        return {
          allowedActions: ['EMOTE', 'SPEAK', 'FLEE', 'IDLE'],
          forbiddenActions: ['ATTACK', 'GIVE_GOLD', 'KILL_PLAYER'],
          maxParamsCount: 2,
        };
    }
  }
}
