# GENERATED by scripts/generate-cardinal.mjs -- do not edit.
#
# Source of truth: cardinal/components.mjs
# Regenerate with: node scripts/generate-cardinal.mjs

defmodule IwsdkPhoenix.Cardinal.Health do
  @moduledoc "Cardinal component 1. 8 bytes on the wire."

  defstruct current: 0.0, max: 0.0

  @type t :: %__MODULE__{
          current: float(),
          max: float(),
        }

  @doc "Wire size in bytes. Constant."
  @spec byte_size() :: pos_integer()
  def byte_size, do: 8

  @doc "Field names in declaration order — struct key order is sorted, not declared."
  @spec field_order() :: [atom()]
  def field_order, do: [:current, :max]

  @spec encode(t()) :: binary()
  def encode(%__MODULE__{} = struct) do
    IO.iodata_to_binary([
      <<struct.current::float-little-size(32)>>,
      <<struct.max::float-little-size(32)>>
    ])
  end

  @spec decode(binary()) :: {:ok, t()} | :error
  def decode(<<current::float-little-size(32), max::float-little-size(32)>>) do
    {:ok,
     %__MODULE__{
       current: current,
       max: max,
     }}
  end

  def decode(_other), do: :error
end

defmodule IwsdkPhoenix.Cardinal.Grabbable do
  @moduledoc "Cardinal component 2. 16 bytes on the wire."

  defstruct holder_id: 0, grab_point: %{x: 0.0, y: 0.0, z: 0.0}

  @type t :: %__MODULE__{
          holder_id: non_neg_integer(),
          grab_point: IwsdkPhoenix.Protocol.vec3(),
        }

  @doc "Wire size in bytes. Constant."
  @spec byte_size() :: pos_integer()
  def byte_size, do: 16

  @doc "Field names in declaration order — struct key order is sorted, not declared."
  @spec field_order() :: [atom()]
  def field_order, do: [:holder_id, :grab_point]

  @spec encode(t()) :: binary()
  def encode(%__MODULE__{} = struct) do
    IO.iodata_to_binary([
      <<struct.holder_id::unsigned-little-integer-size(32)>>,
      <<struct.grab_point.x::float-little-size(32), struct.grab_point.y::float-little-size(32), struct.grab_point.z::float-little-size(32)>>
    ])
  end

  @spec decode(binary()) :: {:ok, t()} | :error
  def decode(<<holder_id::unsigned-little-integer-size(32), grab_point_x::float-little-size(32), grab_point_y::float-little-size(32), grab_point_z::float-little-size(32)>>) do
    {:ok,
     %__MODULE__{
       holder_id: holder_id,
       grab_point: %{x: grab_point_x, y: grab_point_y, z: grab_point_z},
     }}
  end

  def decode(_other), do: :error
end

defmodule IwsdkPhoenix.Cardinal.Registry do
  @moduledoc """
  Lookup from wire id to generated component module.

  Unknown ids return `nil` rather than raising: the join-time schema hash
  check rules out drift, so an unknown id can only be a bug, and a bug must
  not take the room down with it.
  """

  @schema_hash "4aa9aec1"

  @spec schema_hash() :: String.t()
  def schema_hash, do: @schema_hash

  @spec ids() :: [pos_integer()]
  def ids, do: [1, 2]

  @spec module_for(integer()) :: module() | nil
  def module_for(1), do: IwsdkPhoenix.Cardinal.Health
  def module_for(2), do: IwsdkPhoenix.Cardinal.Grabbable
  def module_for(_other), do: nil

  @spec byte_size_for(integer()) :: pos_integer() | nil
  def byte_size_for(1), do: 8
  def byte_size_for(2), do: 16
  def byte_size_for(_other), do: nil
end
